# Generated by Django 5.1.4 on 2024-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0002_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='in_scope',
            field=models.BooleanField(default=False, help_text='If the division is target for the learning program, check this field.'),
            preserve_default=False,
        ),
    ]
